import type {
  AllocationCycle,
  Application,
  Hostel,
  User,
} from '../types';
import { encryptLifestyleData } from './encryption';

export const INITIAL_USERS: User[] = [
  {
    id: 'user-stu-1',
    name: 'Arjun Patel',
    email: 'arjun.p@univ.edu',
    role: 'STUDENT',
    rollNumber: '2024CS101',
    gender: 'MALE',
    department: 'Computer Science',
    year: 3,
    cgpa: 8.9,
    distanceKm: 420,
    feeCleared: true,
    disciplinaryAction: false,
    isPwD: false,
    category: 'GENERAL',
  },
  {
    id: 'user-stu-2',
    name: 'Rohan Verma',
    email: 'rohan.v@univ.edu',
    role: 'STUDENT',
    rollNumber: '2024CS102',
    gender: 'MALE',
    department: 'Computer Science',
    year: 3,
    cgpa: 8.6,
    distanceKm: 380,
    feeCleared: true,
    disciplinaryAction: false,
    isPwD: false,
    category: 'OBC',
  },
  {
    id: 'user-stu-3',
    name: 'Priya Sharma',
    email: 'priya.s@univ.edu',
    role: 'STUDENT',
    rollNumber: '2024EC201',
    gender: 'FEMALE',
    department: 'Electronics',
    year: 2,
    cgpa: 9.1,
    distanceKm: 650,
    feeCleared: true,
    disciplinaryAction: false,
    isPwD: false,
    category: 'GENERAL',
  },
  {
    id: 'user-stu-4',
    name: 'Ananya Iyer',
    email: 'ananya.i@univ.edu',
    role: 'STUDENT',
    rollNumber: '2024EC202',
    gender: 'FEMALE',
    department: 'Electronics',
    year: 2,
    cgpa: 8.7,
    distanceKm: 580,
    feeCleared: true,
    disciplinaryAction: false,
    isPwD: false,
    category: 'GENERAL',
  },
  {
    id: 'user-stu-5',
    name: 'Vikram Malhotra',
    email: 'vikram.m@univ.edu',
    role: 'STUDENT',
    rollNumber: '2024ME301',
    gender: 'MALE',
    department: 'Mechanical',
    year: 4,
    cgpa: 7.9,
    distanceKm: 210,
    feeCleared: true,
    disciplinaryAction: false,
    isPwD: true, // Requires ground floor accessible bed!
    category: 'GENERAL',
  },
  {
    id: 'user-stu-6',
    name: 'Rahul Gupta',
    email: 'rahul.g@univ.edu',
    role: 'STUDENT',
    rollNumber: '2024CS199',
    gender: 'MALE',
    department: 'Computer Science',
    year: 2,
    cgpa: 4.8, // CGPA < 5.0
    distanceKm: 15, // Local day scholar
    feeCleared: false, // Dues pending
    disciplinaryAction: true,
    isPwD: false,
    category: 'GENERAL',
  },
  {
    id: 'user-warden-1',
    name: 'Dr. S. Sharma',
    email: 'warden.aryabhatta@univ.edu',
    role: 'WARDEN',
    assignedHostelId: 'hostel-aryabhatta',
    department: 'Hostel Administration',
  },
  {
    id: 'user-chief-warden',
    name: 'Prof. V. Raman',
    email: 'chief.warden@univ.edu',
    role: 'CHIEF_WARDEN',
    department: 'Deanery Office',
  },
  {
    id: 'user-hostel-admin',
    name: 'Admin Verma',
    email: 'hostel.admin@univ.edu',
    role: 'HOSTEL_ADMIN',
    department: 'Estate & Hostel Ops',
  },
  {
    id: 'user-dsw',
    name: 'Prof. Meenakshi Sundaram',
    email: 'dsw@univ.edu',
    role: 'DSW',
    department: 'Dean of Student Welfare',
  },
  {
    id: 'user-sys-admin',
    name: 'System Administrator',
    email: 'sysadmin@univ.edu',
    role: 'SYS_ADMIN',
    department: 'IT Infrastructure',
  },
];

export function generateInitialHostels(): Hostel[] {
  return [
    {
      id: 'hostel-aryabhatta',
      name: 'Aryabhatta Hall of Residence',
      code: 'ARY',
      genderPolicy: 'MALE',
      description: 'Senior Undergraduate & Postgraduate Men’s Hall with sports complex and Wi-Fi 6',
      amenities: ['High-speed Wi-Fi', 'Study Hall', 'Badminton Court', 'Laundry', 'Solar Geysers'],
      totalCapacity: 48,
      currentOccupancy: 0,
      blocks: [
        {
          id: 'block-ary-a',
          hostelId: 'hostel-aryabhatta',
          name: 'Block A (Main Wing)',
          genderPolicy: 'MALE',
          floors: [0, 1, 2].map((fNum) => ({
            id: `floor-ary-a-${fNum}`,
            blockId: 'block-ary-a',
            hostelId: 'hostel-aryabhatta',
            floorNumber: fNum,
            name: fNum === 0 ? 'Ground Floor (Accessible)' : `Floor ${fNum}`,
            hasElevator: true,
            hasRamp: fNum === 0,
            rooms: [1, 2, 3, 4].map((rIndex) => {
              const roomNumber = `${fNum}0${rIndex}`;
              const isAccessible = fNum === 0 && rIndex <= 2;
              const isQuietZone = rIndex >= 3;
              const type = rIndex % 2 === 0 ? 'DOUBLE_AC' : 'DOUBLE_NON_AC';
              return {
                id: `room-ary-a-${roomNumber}`,
                floorId: `floor-ary-a-${fNum}`,
                blockId: 'block-ary-a',
                hostelId: 'hostel-aryabhatta',
                roomNumber,
                capacity: 2,
                type,
                isAccessible,
                isQuietZone,
                hasAttachedBath: rIndex % 2 === 0,
                beds: [
                  {
                    id: `bed-ary-${roomNumber}-A`,
                    roomId: `room-ary-a-${roomNumber}`,
                    bedCode: 'A',
                    status: 'VACANT',
                  },
                  {
                    id: `bed-ary-${roomNumber}-B`,
                    roomId: `room-ary-a-${roomNumber}`,
                    bedCode: 'B',
                    status: 'VACANT',
                  },
                ],
              };
            }),
          })),
        },
      ],
    },
    {
      id: 'hostel-gargi',
      name: 'Gargi Hall of Residence',
      code: 'GAR',
      genderPolicy: 'FEMALE',
      description: 'Women’s Hall of Residence with high-security access, garden quad, and gym',
      amenities: ['24/7 Security Guard', 'Gymnasium', 'Music Room', 'Solar Hot Water', 'Mess Cafeteria'],
      totalCapacity: 36,
      currentOccupancy: 0,
      blocks: [
        {
          id: 'block-gar-main',
          hostelId: 'hostel-gargi',
          name: 'Main Block',
          genderPolicy: 'FEMALE',
          floors: [0, 1].map((fNum) => ({
            id: `floor-gar-${fNum}`,
            blockId: 'block-gar-main',
            hostelId: 'hostel-gargi',
            floorNumber: fNum,
            name: fNum === 0 ? 'Ground Floor (Accessible)' : `Floor ${fNum}`,
            hasElevator: true,
            hasRamp: fNum === 0,
            rooms: [1, 2, 3].map((rIndex) => {
              const roomNumber = `${fNum}0${rIndex}`;
              const isAccessible = fNum === 0;
              const isQuietZone = rIndex === 3;
              const type = rIndex === 1 ? 'SINGLE_AC' : 'DOUBLE_AC';
              const capacity = rIndex === 1 ? 1 : 2;
              return {
                id: `room-gar-${roomNumber}`,
                floorId: `floor-gar-${fNum}`,
                blockId: 'block-gar-main',
                hostelId: 'hostel-gargi',
                roomNumber,
                capacity,
                type,
                isAccessible,
                isQuietZone,
                hasAttachedBath: true,
                beds: Array.from({ length: capacity }, (_, i) => ({
                  id: `bed-gar-${roomNumber}-${String.fromCharCode(65 + i)}`,
                  roomId: `room-gar-${roomNumber}`,
                  bedCode: String.fromCharCode(65 + i),
                  status: 'VACANT',
                })),
              };
            }),
          })),
        },
      ],
    },
    {
      id: 'hostel-kalam',
      name: 'Kalam Research Tower',
      code: 'KAL',
      genderPolicy: 'MALE',
      description: 'Executive scholar residence with individual study carrels and silent floors',
      amenities: ['Attached Kitchenette', 'Silent Library', 'Conference Room', 'AC Gym'],
      totalCapacity: 24,
      currentOccupancy: 0,
      blocks: [
        {
          id: 'block-kal-east',
          hostelId: 'hostel-kalam',
          name: 'East Wing',
          genderPolicy: 'MALE',
          floors: [0, 1].map((fNum) => ({
            id: `floor-kal-${fNum}`,
            blockId: 'block-kal-east',
            hostelId: 'hostel-kalam',
            floorNumber: fNum,
            name: fNum === 0 ? 'Ground Floor' : `Floor ${fNum}`,
            hasElevator: true,
            hasRamp: true,
            rooms: [1, 2].map((rIndex) => {
              const roomNumber = `${fNum}1${rIndex}`;
              return {
                id: `room-kal-${roomNumber}`,
                floorId: `floor-kal-${fNum}`,
                blockId: 'block-kal-east',
                hostelId: 'hostel-kalam',
                roomNumber,
                capacity: 2,
                type: 'DOUBLE_AC',
                isAccessible: fNum === 0,
                isQuietZone: true,
                hasAttachedBath: true,
                beds: [
                  {
                    id: `bed-kal-${roomNumber}-A`,
                    roomId: `room-kal-${roomNumber}`,
                    bedCode: 'A',
                    status: 'VACANT',
                  },
                  {
                    id: `bed-kal-${roomNumber}-B`,
                    roomId: `room-kal-${roomNumber}`,
                    bedCode: 'B',
                    status: 'VACANT',
                  },
                ],
              };
            }),
          })),
        },
      ],
    },
  ];
}

export const INITIAL_CYCLE: AllocationCycle = {
  id: 'cycle-2026-odd',
  academicYear: '2026-2027',
  semester: 'ODD',
  startDate: '2026-08-01',
  endDate: '2026-12-15',
  status: 'OPEN',
  eligibleGenders: ['MALE', 'FEMALE', 'OTHER'],
  totalApplications: 6,
  allocatedCount: 0,
};

export function generateInitialApplications(): Application[] {
  return [
    {
      id: 'app-arjun',
      cycleId: 'cycle-2026-odd',
      studentId: 'user-stu-1',
      studentRoll: '2024CS101',
      studentName: 'Arjun Patel',
      gender: 'MALE',
      isPwD: false,
      cgpa: 8.9,
      distanceKm: 420,
      feeCleared: true,
      category: 'GENERAL',
      eligibilityStatus: 'ELIGIBLE',
      eligibilityReasons: ['Passed all policy rules (Fee Cleared, CGPA > 5.0, Distance > 25km)'],
      submissionDate: '2026-08-10T09:30:00Z',
      preferences: {
        rankedHostels: ['hostel-aryabhatta', 'hostel-kalam'],
        preferredRoomTypes: ['DOUBLE_AC', 'SINGLE_AC'],
        preferredRoommates: ['2024CS102'],
        requireAccessible: false,
        preferQuietZone: true,
      },
      lifestyleScores: {
        sleepSchedule: 4,
        studyHabit: 2,
        cleanliness: 4,
        guestFrequency: 2,
        temperatureComfort: 2,
        foodHabit: 'VEG',
      },
      lifestyleEncrypted: encryptLifestyleData({
        sleepSchedule: 4,
        studyHabit: 2,
        cleanliness: 4,
        guestFrequency: 2,
        temperatureComfort: 2,
        foodHabit: 'VEG',
      }),
    },
    {
      id: 'app-rohan',
      cycleId: 'cycle-2026-odd',
      studentId: 'user-stu-2',
      studentRoll: '2024CS102',
      studentName: 'Rohan Verma',
      gender: 'MALE',
      isPwD: false,
      cgpa: 8.6,
      distanceKm: 380,
      feeCleared: true,
      category: 'OBC',
      eligibilityStatus: 'ELIGIBLE',
      eligibilityReasons: ['Passed all policy rules'],
      submissionDate: '2026-08-10T10:15:00Z',
      preferences: {
        rankedHostels: ['hostel-aryabhatta', 'hostel-kalam'],
        preferredRoomTypes: ['DOUBLE_AC'],
        preferredRoommates: ['2024CS101'],
        requireAccessible: false,
        preferQuietZone: true,
      },
      lifestyleScores: {
        sleepSchedule: 4,
        studyHabit: 2,
        cleanliness: 4,
        guestFrequency: 2,
        temperatureComfort: 2,
        foodHabit: 'VEG',
      },
      lifestyleEncrypted: encryptLifestyleData({
        sleepSchedule: 4,
        studyHabit: 2,
        cleanliness: 4,
        guestFrequency: 2,
        temperatureComfort: 2,
        foodHabit: 'VEG',
      }),
    },
    {
      id: 'app-priya',
      cycleId: 'cycle-2026-odd',
      studentId: 'user-stu-3',
      studentRoll: '2024EC201',
      studentName: 'Priya Sharma',
      gender: 'FEMALE',
      isPwD: false,
      cgpa: 9.1,
      distanceKm: 650,
      feeCleared: true,
      category: 'GENERAL',
      eligibilityStatus: 'ELIGIBLE',
      eligibilityReasons: ['Passed all policy rules'],
      submissionDate: '2026-08-11T14:00:00Z',
      preferences: {
        rankedHostels: ['hostel-gargi'],
        preferredRoomTypes: ['DOUBLE_AC', 'SINGLE_AC'],
        preferredRoommates: ['2024EC202'],
        requireAccessible: false,
        preferQuietZone: false,
      },
      lifestyleScores: {
        sleepSchedule: 2,
        studyHabit: 3,
        cleanliness: 5,
        guestFrequency: 3,
        temperatureComfort: 3,
        foodHabit: 'ANY',
      },
      lifestyleEncrypted: encryptLifestyleData({
        sleepSchedule: 2,
        studyHabit: 3,
        cleanliness: 5,
        guestFrequency: 3,
        temperatureComfort: 3,
        foodHabit: 'ANY',
      }),
    },
    {
      id: 'app-ananya',
      cycleId: 'cycle-2026-odd',
      studentId: 'user-stu-4',
      studentRoll: '2024EC202',
      studentName: 'Ananya Iyer',
      gender: 'FEMALE',
      isPwD: false,
      cgpa: 8.7,
      distanceKm: 580,
      feeCleared: true,
      category: 'GENERAL',
      eligibilityStatus: 'ELIGIBLE',
      eligibilityReasons: ['Passed all policy rules'],
      submissionDate: '2026-08-11T15:20:00Z',
      preferences: {
        rankedHostels: ['hostel-gargi'],
        preferredRoomTypes: ['DOUBLE_AC'],
        preferredRoommates: ['2024EC201'],
        requireAccessible: false,
        preferQuietZone: false,
      },
      lifestyleScores: {
        sleepSchedule: 2,
        studyHabit: 3,
        cleanliness: 5,
        guestFrequency: 3,
        temperatureComfort: 3,
        foodHabit: 'ANY',
      },
      lifestyleEncrypted: encryptLifestyleData({
        sleepSchedule: 2,
        studyHabit: 3,
        cleanliness: 5,
        guestFrequency: 3,
        temperatureComfort: 3,
        foodHabit: 'ANY',
      }),
    },
    {
      id: 'app-vikram',
      cycleId: 'cycle-2026-odd',
      studentId: 'user-stu-5',
      studentRoll: '2024ME301',
      studentName: 'Vikram Malhotra',
      gender: 'MALE',
      isPwD: true,
      cgpa: 7.9,
      distanceKm: 210,
      feeCleared: true,
      category: 'GENERAL',
      eligibilityStatus: 'ELIGIBLE',
      eligibilityReasons: ['Passed policy rules with PwD Medical Priority for Ground Floor'],
      submissionDate: '2026-08-12T11:00:00Z',
      preferences: {
        rankedHostels: ['hostel-aryabhatta'],
        preferredRoomTypes: ['DOUBLE_NON_AC', 'DOUBLE_AC'],
        preferredRoommates: [],
        requireAccessible: true,
        preferQuietZone: false,
      },
      lifestyleScores: {
        sleepSchedule: 3,
        studyHabit: 2,
        cleanliness: 3,
        guestFrequency: 2,
        temperatureComfort: 3,
        foodHabit: 'NON_VEG',
      },
      lifestyleEncrypted: encryptLifestyleData({
        sleepSchedule: 3,
        studyHabit: 2,
        cleanliness: 3,
        guestFrequency: 2,
        temperatureComfort: 3,
        foodHabit: 'NON_VEG',
      }),
    },
    {
      id: 'app-rahul',
      cycleId: 'cycle-2026-odd',
      studentId: 'user-stu-6',
      studentRoll: '2024CS199',
      studentName: 'Rahul Gupta',
      gender: 'MALE',
      isPwD: false,
      cgpa: 4.8,
      distanceKm: 15,
      feeCleared: false,
      category: 'GENERAL',
      eligibilityStatus: 'INELIGIBLE',
      eligibilityReasons: [
        'Outstanding semester fee dues pending in ERP/Finance account.',
        'CGPA is below the minimum threshold (5.00) for hostel residency.',
        'Local day-scholar distance is under the 25 KM priority limit.',
        'Active disciplinary probation recorded with Proctor office.',
      ],
      submissionDate: '2026-08-12T16:45:00Z',
      preferences: {
        rankedHostels: ['hostel-aryabhatta'],
        preferredRoomTypes: ['DOUBLE_AC'],
        preferredRoommates: [],
        requireAccessible: false,
        preferQuietZone: false,
      },
      lifestyleScores: {
        sleepSchedule: 5,
        studyHabit: 5,
        cleanliness: 1,
        guestFrequency: 5,
        temperatureComfort: 1,
        foodHabit: 'ANY',
      },
      lifestyleEncrypted: encryptLifestyleData({
        sleepSchedule: 5,
        studyHabit: 5,
        cleanliness: 1,
        guestFrequency: 5,
        temperatureComfort: 1,
        foodHabit: 'ANY',
      }),
    },
  ];
}
